services:
  backend:
    container_name: backend-tattoo-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    dns:
      - 8.8.8.8
      - 8.8.4.4
